def returnData():
	nominees = [["argo", "django unchained", "life of pi", "lincoln", "zero dark thirty"], 
		["les miserables", "the best exotic marigold hotel", "moonrise kingdom", "salmon fishing in the yemen", "silver linings playbook"], 
		["daniel day-lewis","richard gere", "john hawkes", "joaquin phoenix", "denzel washington"], 
		["jessica chastain", "marion cotillard", "sally field", "helen mirren", "naomi watts", "rachel weisz"], 
		["hugh jackman","jack black", "bradley cooper", "ewan mcgregor", "bill murray"], 
		["jennifer lawrence","emily blunt", "judi dench", "maggie smith", "meryl streep"], 
		["christoph waltz","alan arkin", "leonardo dicaprio", "philip seymour hoffman", "tommy lee jones"], 
		["anne hathaway","amy adams", "sally field", "helen hunt", "nicole kidman"], 
		["ben affleck","kathryn bigelow", "ang lee", "steven spielberg", "quentin tarantino"], 
		["zero dark thirty", "lincoln", "silver linings playbook", "argo","django unchained"], 
		["life of pi","argo", "anna karenina", "cloud atlas", "lincoln"], 
		["skyfall", "act of valor", "stand up guys", "the hunger games", "les miserables"], 
		["brave","frankenweenie", "hotel transylvania", "rise of the guardians", "wreck-it ralph"], 
		["amour","the intouchables", "kon tiki", "a royal affair", "rust and bone"], 
		["homeland","boardwalk empire", "breaking bad", "downton abbey (masterpiece)", "the newsroom"], 
		["claire danes","connie britton", "glenn close", "michelle dockery", "julianna margulies"], 
		["steve buscemi", "bryan cranston", "jeff daniels", "jon hamm","damian lewis"], 
		["girls", "the big bang theory", "episodes", "modern family", "smash"], 
		["lena dunham","zooey deschanel", "tina fey", "julia louis-dreyfus", "amy poehler"], 
		["alec baldwin", "louis c.k.", "matt leblanc", "jim parsons", "don cheadle"],
		["game change","the girl", "hatfields & mccoys", "the hour", "political animals"], 
		["julianne moore", "nicole kidman", "jessica lange", "sienna miller", "sigourney weaver"], 
		["kevin costner","benedict cumberbatch", "woody harrelson", "toby jones", "clive owen"], 
		["maggie smith","hayden panettiere", "archie panjabi", "sarah paulson", "sofia vergara"], 
		["ed harris","max greenfield", "danny huston", "mandy patinkin", "eric stonestreet"],
		["jodie foster"]]

	presenter_list = ["will ferrell", 
					"kate hudson", 
					"sacha baron cohen",
					"john krasinski", 
					"aziz ansari", 
					"julia roberts", 
					"don cheadle", 
					"kristen wiig", 
					"arnold schwarzenegger",
					"lucy liu", "nathan fillion", 
					"jay leno",
					"sylvester stallone", 
					"jonah hill", 
					"jimmy fallon",
					"kiefer sutherland", 
					"jason statham", 
					"jessica alba",
					"george clooney",
					"dennis quaid",
					"robert pattinson", 
					"halle berry", 
					"kristen bell", 
					"lea michele", 
					"salma hayek", 
					"jennifer lopez", 
					"dustin hoffman",
					"amanda seyfried",
					"kerry washington", 
					"debra messing",
					"eva longoria",
					"jennifer garner",
					"megan fox", 
					"paul rudd", 
					"jason bateman",
					"bradley cooper",
					"robert downey, jr."]
	return (nominees, presenter_list)